name: Scheduled Pinger
on:
schedule:
# Runs "at minute 0 past every 3 hour" (see https://crontab.guru)...
- cron: '0 */3 * * *'
workflow_dispatch:

jobs:
build-and-probe:
runs-on: ubuntu-latest
steps:
  - name: Checkout Repository
    uses: actions/checkout@v2
  - name: Build Docker Image
    run: docker build -t my-probe-image -f probe-action/Dockerfile .

  - name: Run Docker Container
    run: docker run --rm my-probe-image
    name: A job to probe deployed app
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Probe Deployed App Action Step
        uses: ./probe-action # Uses an action in the probe-action directory
        id: probe